version: '3.3'
services:
  nginx:
    image: nginx:latest 
    ports:
      - "80:80"
    volumes:
      - ${ELK_MAIN_HOST_FOLDER}/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${ELK_MAIN_HOST_FOLDER}/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
            - elk
    deploy:
      placement:
        constraints:
          - node.hostname==${ELK_MAIN_HOST}
networks:
  elk:
    driver: overlay
    attachable: true
 
 
